name: 'Create Release'
description: 'Create a GitHub Release'
branding:
  icon: 'package'
  color: 'green'
inputs:
  name:
    description: "Release Name"
    required: true
  tag_name:
    description: "Tag Name"
    required: true
  token:
    description: "Github Token"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.repository }}
    - ${{ inputs.name }}
    - ${{ inputs.tag_name }}
    - ${{ inputs.token }}
