name: 'Create Release from PR'
description: 'Create a GitHub release from a PR'
branding:
  icon: 'package'
  color: 'green'
inputs:
  token:
    description: "Github token (with release permissions)"
    required: true
  repo:
    description: "Source repository"
    required: true
  pr_title:
    description: "Pull Request title"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repo }}
    - ${{ inputs.pr_title }}
