name: 'Create Release from PR'
description: 'Create a GitHub release from a PR'
branding:
  icon: 'package'
  color: 'green'
inputs:
  token:
    description: "Github Token"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ github.repository }}
    - ${{ github.event.pull_request.title }}
