name: test

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  create-release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    -
      name: Create Release
      uses: bfren/create-release@main
      with:
        token: ${{ secrets.PAT }}
